# 오류(error)의 종류
* 프로그램 실행 전에 발생하는 오류: 구문 오류(syntax error)
* 프로그램 실행 중에 발생하는 오류: 예외(exception) 또는 런타임 오류(runtime error)

## 구문 오류(syntax error)
괄호의 개수, 들여쓰기 문제 등으로 프로그램이 실행되기도 전에 발생하는 오류  
EOL: End Of Line  
SyntaxError는 구문에 문제가 있어 프로그램이 실행조차 되지 않는 오류

## 예외(exception)
프로그램이 일단 실행된 다음, 실행 중에 발생하는 오류를 예외 또는 런타임 오류라고 부름.

## 기본 예외 처리
예외를 해결하는 모든 것을 예외 처리(exception handling)라고 함.
* 조건문 사용
* try 구문 사용

### 조건문으로 예외 처리
int(input("정수 입력> ")) 같은 구문에서 정수를 입력하지 않았을 때를 조건으로 구분해서 해당 상황일 때 다른 처리를 하도록 설정.  
isdigit() 함수를 사용해서 숫자로만 구성된 글자인지 확인.
```
# 숫자 입력받기
user_input_a = input("정수 입력> ")

# 사용자 입력이 숫자로만 구성되어 있을 때
if user_input_a.isdigit():
  # 숫자로 변환
  number_input_a = int(user_input_a)
  # 출력
  print("원의 반지름: ", number_input_a)
  print("원의 둘레: ", 2 * 3.14 * number_input_a)
  print("원의 넓이: ", 3.14 * number_input_a * number_input_a)
else:
  print("정수를 입력하지 않았습니다.")
```

### try except 구문
예외가 발생할 상황을 예측하고 모두 조건문으로 처리하는 것은 매우 힘듬. 조건문만으로 예외를 처리할 수 없는 경우도 있음.  
예외를 처리할 수 있는 구문이 try except 구문.
```
try:
  예외가 발생할 가능성이 있는 코드
except:
  예외가 발생했을 때 실행할 코드
```
예외가 발생할 가능성이 있는 코드를 모두 try 구문 안에 넣고 예외가 발생했을 때 실행할 코드를 모두 except 구문 안에 넣으면 됨.
```
# try except 구문으로 예외 처리
try:
  # 숫자로 변환
  number_input_a = int(input("정수 입력> "))    # 예외가 발생할 가능성이 있는 구문
  # 출력
  print("원의 반지름: ", number_input_a)
  print("원의 둘레: ", 2 * 3.14 * number_input_a)
  print("원의 넓이: ", 3.14 * number_input_a * number_input_a)
except:
  print("무언가 잘못되었습니다.")    # 예외가 발생했을 때 실행할 구문
```
#### try except 구문과 pass 키워드 조합
해당 코드가 딱히 중요한 부분이 아니라면 일단 프로그램이 강제 종료되는 것부터 막자는 목적으로 except 구문에 아무 것도 넣지 않고 try 구문 사용  
구문 내부에 아무 것도 넣지 않으면 구문 오류가 발생하므로 다음과 같이 pass 키워드를 넣어줌.
```
try:
  예외 발생 가능성 있는 코드
except:
  pass
```
```
# 변수 선언
list_input_a = ["52", "273", "32", "스파이", "103"]

# 반복 적용
list_number = []
for item in list_input_a:
  # 숫자로 변환해서 리스트에 추가
  try:
    float(item)
    list_number.append(item)
  except:
    pass

# 출력
print("{} 내부에 있는 숫자는".format(list_input_a))
print("{} 입니다.".format(list_number))

# 실행 결과
# ['52', '273', '32', '스파이', '103'] 내부에 있는 숫자는
# ['52', '273', '32', '103'] 입니다.
```

#### try except else 구문
```
try:
  예외가 발생할 가능성이 있는 코드
except:
  예외가 발생했을 때 실행할 코드
else:
  예외가 발생하지 않았을 때 실행할 코드
```
```
# try except else 구문 예외 처리
try:
  # 숫자 변환
  number_input_a = int(input("정수 입력> "))
except:
  print("정수를 입력하지 않았습니다.")
else:
  # 출력
  print("원의 반지름: ", number_input_a)
  print("원의 둘레: ", 2 * 3.14 * number_input_a)
  print("원의 넓이: ", 3.14 * number_input_a * number_input_a)
```
예외 처리에 else 구문이 있는 프로그래밍 언어는 파이썬과 루비 정도. 몇몇 프로그래밍 언어만 가지고 있는 기능은 다른 말로 하면, 그 기능이 없어도 프로그램을 만드는 데는 문제가 없다는 의미. 다른 사람이 만든 코드를 이해할 정도로 학습.
#### finally 구문
예외 처리 구문에서 가장 마지막에 사용할 수 있는 구문. 예외 발생 여부와 무관하게 수행.
```
try:
  예외가 발생할 가능성이 있는 코드
except:
  예외가 발생했을 때 실행할 코드
else:
  예외가 발생하지 않았을 때 실행할 코드
finally:
  무조건 실행할 코드
```
